const data = {
    en: {
        Action_AmendBooking: 'Amend Booking',
        Action_Back: 'Back',
        Action_Book: 'Book',
        Action_Continue: 'Continue...',
        Action_Download: 'Download',
        Action_Go: 'Go',
        Action_Lookup: 'Lookup',
        Action_NewBooking: 'Start New Booking',
        Action_Print: 'Print',
        Action_Remove: 'Remove',
        Action_Send: 'Send',
        Action_SendRequest: 'Send Request',
        Action_Submit: 'Submit',
        Action_ViewAll: ' View all',
        AddOnRequestSent: 'Your request has been sent',
        AddonTerms: 'By clicking \'Send Request\', you agree to our Terms and Conditions & Privacy Policy when requesting additional services',
        Amount: 'Amount',
        Availability_None_FriendlyMessage: 'Sorry, we are unable to accommodate your selection, please contact us on {0} for further assitance.',
        Bookd_Email_Label: 'Email',
        Bookd_Facilities_Label: ' Facilities',
        Bookd_OpeningHours_And: ' and',
        Bookd_OpeningHours_Closed: 'Closed',
        Bookd_OpeningHours_Label: ' Opening Times',
        Bookd_OpeningHours_NotSet: 'Please contact your garage for opening times',
        Bookd_Telephone_Label: 'Telephone',
        Bookd_Website_Label: 'Website',
        BookdMoreDetails: 'more details...',
        BookdNoPackages: 'No Services or Packages available',
        Booking_ContactDetails: 'Your details',
        Booking_Date: ' Date',
        Booking_DropOff: 'Drop off',
        Booking_VehicleDetails: 'Your vehicle',
        BookingConfirmation: 'Confirm booking',
        BookingService_Error_AvailabilityExpired: 'Sorry, it seems like that booking is no longer available',
        BookingService_Error_NoAvailability: 'Sorry, we don\'t have available capacity to book you in, please try another day or time',
        ChangeVehicleType: 'Change type',
        Communication_YourMessage: 'Send { 0}',
        Communications_NoneFound: 'Please send us a message if you have any questions',
        ConfirmationMessageOnAutoAccept: 'Shortly you\'ll receive an email containing your booking details along with details to access our CustomerLounge.',
ConfirmationMessageOnEnquiry: 'Thank you for your enquiry.',
        We: 'will respond as quickly as we can to confirm your appointment.',
        Copyright: 'Copyright',
        CustomerLoungeAddOnTerms: 'View Terms and Conditions & Privacy Policy',
        DetailsViewModel_CustomerEmail: 'Email',
        DetailsViewModel_CustomerFirstName: 'First name',
        DetailsViewModel_CustomerLastName: 'Last name',
        DetailsViewModel_CustomerMobile: 'Mobile',
        DetailsViewModel_CustomerPostcode: 'Postcode',
        DetailsViewModel_CustomerTelephone: 'Telephone',
        DetailsViewModel_CustomerTitle: 'Title',
        DetailsViewModel_ReCaptcha: 'ReCaptcha',
        DetailsViewModel_StateOfRegistration: 'State of Registration',
        DetailsViewModel_TermsAndConditions: 'Terms and Conditions & Privacy Policy',
        DetailsViewModel_VehicleMake: 'Vehicle make',
        DetailsViewModel_VehicleModel: 'Vehicle model',
        DetailsViewModel_VehicleReg: 'Vehicle registration',
        DetailsViewModel_VehicleRego: ' Rego',
        Error: 'Error',
        Error_Generic: 'An error occurred while processing your request.',
        Error_InvalidToken: 'Your link is invalid',
        Error_SessionExpired: ' Your session has expired',
        Garage_Location: 'Location',
        GarageLocation: 'Location',
        Header_BookingCheck: 'Check your booking',
        Header_BookingDetails: 'Summary & Your Details',
        Header_Communications: 'Messages',
        Header_ContactInfo: 'Contact Info',
        Header_CustomerLounge: 'CustomerLounge',
        Header_DateSelect: 'Select your date & time',
        Header_GarageDetection: ' Welcome to Bookd',
        Header_JobDetails: 'Job details - { 0}',
        Header_Summary: 'Your Booking',
        Hours: 'Hours',
        Item: ' item',
        Items: 'items',
        JobCodeViewModel_Code: 'Code',
        JobDetails: ' Job details',
        JobViewModel_In: 'In',
        JobViewModel_Out: 'Out',
        Label_Booked: 'Booked',
        Label_CompanyNumber: 'Company Number',
        Label_Done: ' Done',
        Label_InProgress: ' In Progress',
        Label_SelectDerivative: 'Select Derivative',
        Label_SelectMake: ' Select Make',
        Label_SelectModel: 'Select Model',
        Label_SelectYear: ' Select Year',
        Label_TaxNumber: 'VAT Number',
        Lounge_AddToMyRepairs: 'Add to my repairs',
        Lounge_Close: 'Close',
        Lounge_CloseModal: 'Close modal',
        Lounge_CommHello: ' Hello {0}',
        Lounge_CommWelcome: 'Welcome to your booking',
        Lounge_DateTimeIn: 'Date/Time in:',
        Lounge_DueOut: 'Due out:',
        Lounge_GetDirections: 'Get directions',
        Lounge_Header_AllOffers: 'All offers',
        Lounge_Message: 'Message',
        Lounge_SubHeader_Files: 'Files',
        Lounge_SubHeader_HowToFindUs: 'How to find us',
        Lounge_SubHeader_Summary_AdditionalPackages: 'You may also be interested in...',
        Lounge_Total: 'Total',
        Lounge_ViewMoreInfo: 'View more info',
        Lounge_WhatYoureHavingDone: 'What you\'re having done',
        Lounge_XClose: 'X Close',
        Lounge_YourServiceAdvisorIs: 'Your service advisor for this job is {0}.',
        Lounge_YourSpeakingTo: 'You\'re speaking to {0}...',
        LoungeJob_Code: 'Please enter your code',
        LoungeJob_Error_InvalidLoungeJobCode: ' Invalid code',
        LoungeJob_Error_InvalidToken: 'That token doesnt seem to be valid',
        LoungeJob_Error_InvalidUserClaims: 'There seems to be an authentication problem',
        LoungeJob_Error_Job_Not_Found: 'This job could not be found',
        LoungeJob_Error_LoungeJobExpired: ' Your job is no longer available',
        LoungeJob_Error_LoungeJobNotYetAvailable: ' Your job is not yet available',
        LoungeJob_Error_NoJobFound: ' We couldn\'t find the job you are looking for',
        MessageSent: 'Message Sent',
        MessageSentMessage: ' Your message has been sent',
        MoreInfo: ' More info',
        NoAdvisorFound: 'No advisor is on the job yet',
        OnlineBookingConfirmation: 'Shortly you\'ll receive an email containing your booking details along with details to access our CustomerLounge',
        PackageSelectViewModel_Selection: 'service or package',
        PassengerVehicle: 'Passenger Vehicle',
        ReCaptchaInvalid: ' Your reCaptcha attempt is invalid.Please try again.',
        Registration: 'Rego',
        Repair: 'Repair',
        RepairList: 'Your repairs',
        Repairs: 'Repairs',
        requestedupsell: 'Requested:',
        RequestSent: 'Request Sent',
        SelectStateOfRegistration: 'Please Select State of Registraion',
        SelectVehicleType: 'Please select your vehicle type.',
        Sent: 'Sent',
        SubHeader_BookingConfirmation: 'Booking Confirmation',
        SubHeader_BookingDetails: ' Booking Details',
        SubHeader_BookingDetails_Summary: 'Booking Summary',
        SubHeader_DateSelect_PickADate: ' Select a date from the calendar',
        SubHeader_GarageDetection_TokenInvalid: 'This garage does not exist',
        SubHeader_Summary_AdditionalPackages: 'These may interest you...',
        SubHeader_Summary_BookingSummary: 'Booking Summary',
        SubHeader_ThanksForBooking: ' Thanks for booking with {0}',
        Success: 'Success',
        TermsAndConditions: 'Term and Conditions & Privacy Policy',
        TermsAndConditionsDesc: 'By checking the box you are agreeing to our Terms and Conditions & Privacy Policy.',
        Today: 'Today',
        Total: 'Total',
  
        VehicleValidationMessage: ' Please select the vehicle type',
        ViewTermsAndConditions: ' View Terms and Conditions & Privacy Policy',
        Welcome_Message: 'Welcome to Bookd',
        WelcomeOnlineBooking_Tag: 'Welcome to Quick Lane Online Booking !',
        You: 'You',
        YourAddress: 'Your address',
        YourAdvisor: 'Your advisor is: ',
        YourBookingReference: 'Your Booking Reference: {0}',
        YourDetails: 'Your details',
        YourRef: 'Your Ref: {0}',
        YourVehicle: 'Your vehicle'
    },
    qwerty: { Action_AmendBooking: 'QWERTY',
    Action_Back: 'QWERTY',
    Action_Book: 'QWERTY',
    Action_Continue: 'QWERTY',
    Action_Download: 'QWERTY',
    Action_Go: 'QWERTY',
    Action_Lookup: 'QWERTY',
    Action_NewBooking: 'QWERTY',
    Action_Print: 'QWERTY',
    Action_Remove: 'QWERTY',
    Action_Send: 'QWERTY',
    Action_SendRequest: 'QWERTY',
    Action_Submit: 'QWERTY',
    Action_ViewAll: 'QWERTY',
    AddOnRequestSent: 'QWERTY',
    AddonTerms: 'QWERTY',
    Amount: 'QWERTY',
    Availability_None_FriendlyMessage: 'QWERTY',
    Bookd_Email_Label: 'QWERTY',
    Bookd_Facilities_Label: 'QWERTY',
    Bookd_OpeningHours_And: 'QWERTY',
    Bookd_OpeningHours_Closed: 'QWERTY',
    Bookd_OpeningHours_Label: 'QWERTY',
    Bookd_OpeningHours_NotSet: 'QWERTY',
    Bookd_Telephone_Label: 'QWERTY',
    Bookd_Website_Label: 'QWERTY',
    BookdMoreDetails: 'QWERTY',
    BookdNoPackages: 'QWERTY',
    Booking_ContactDetails: 'QWERTY',
    Booking_Date: 'QWERTY',
    Booking_DropOff: 'QWERTY',
    Booking_VehicleDetails: 'QWERTY',
    BookingConfirmation: 'QWERTY',
    BookingService_Error_AvailabilityExpired: 'QWERTY',
    BookingService_Error_NoAvailability: 'QWERTY',
    ChangeVehicleType: 'QWERTY',
    Communication_YourMessage: 'QWERTY',
    Communications_NoneFound: 'QWERTY',
    ConfirmationMessageOnAutoAccept: 'QWERTY',
    ConfirmationMessageOnEnquiry: 'QWERTY',
    We: 'QWERTY',
    Copyright: 'QWERTY',
    CustomerLoungeAddOnTerms: 'QWERTY',
    DetailsViewModel_CustomerEmail: 'QWERTY',
    DetailsViewModel_CustomerFirstName: 'QWERTY',
    DetailsViewModel_CustomerLastName: 'QWERTY',
    DetailsViewModel_CustomerMobile: 'QWERTY',
    DetailsViewModel_CustomerPostcode: 'QWERTY',
    DetailsViewModel_CustomerTelephone: 'QWERTY',
    DetailsViewModel_CustomerTitle: 'QWERTY',
    DetailsViewModel_ReCaptcha: 'QWERTY',
    DetailsViewModel_StateOfRegistration: 'QWERTY',
    DetailsViewModel_TermsAndConditions: 'QWERTY',
    DetailsViewModel_VehicleMake: 'QWERTY',
    DetailsViewModel_VehicleModel: 'QWERTY',
    DetailsViewModel_VehicleReg: 'QWERTY',
    DetailsViewModel_VehicleRego: 'QWERTY',
    Error: 'QWERTY',
    Error_Generic: 'QWERTY',
    Error_InvalidToken: 'QWERTY',
    Error_SessionExpired: 'QWERTY',
    Garage_Location: 'QWERTY',
    GarageLocation: 'QWERTY',
    Header_BookingCheck: 'QWERTY',
    Header_BookingDetails: 'QWERTY',
    Header_Communications: 'QWERTY',
    Header_ContactInfo: 'QWERTY',
    Header_CustomerLounge: 'QWERTY',
    Header_DateSelect: 'QWERTY',
    Header_GarageDetection: 'QWERTY',
    Header_JobDetails: 'QWERTY',
    Header_Summary: 'QWERTY',
    Hours: 'QWERTY',
    Item: 'QWERTY',
    Items: 'QWERTY',
    JobCodeViewModel_Code: 'QWERTY',
    JobDetails: 'QWERTY',
    JobViewModel_In: 'QWERTY',
    JobViewModel_Out: 'QWERTY',
    Label_Booked: 'QWERTY',
    Label_CompanyNumber: 'QWERTY',
    Label_Done: 'QWERTY',
    Label_InProgress: 'QWERTY',
    Label_SelectDerivative: 'QWERTY',
    Label_SelectMake: 'QWERTY',
    Label_SelectModel: 'QWERTY',
    Label_SelectYear: 'QWERTY',
    Label_TaxNumber: 'QWERTY',
    Lounge_AddToMyRepairs: 'QWERTY',
    Lounge_Close: 'QWERTY',
    Lounge_CloseModal: 'QWERTY',
    Lounge_CommHello: 'QWERTY',
    Lounge_CommWelcome: 'QWERTY',
    Lounge_DateTimeIn: 'QWERTY',
    Lounge_DueOut: 'QWERTY',
    Lounge_GetDirections: 'QWERTY',
    Lounge_Header_AllOffers: 'QWERTY',
    Lounge_Message: 'QWERTY',
    Lounge_SubHeader_Files: 'QWERTY',
    Lounge_SubHeader_HowToFindUs: 'QWERTY',
    Lounge_SubHeader_Summary_AdditionalPackages: 'QWERTY',
    Lounge_Total: 'QWERTY',
    Lounge_ViewMoreInfo: 'QWERTY',
    Lounge_WhatYoureHavingDone: 'QWERTY',
    Lounge_XClose: 'QWERTY',
    Lounge_YourServiceAdvisorIs: 'QWERTY',
    Lounge_YourSpeakingTo: 'QWERTY',
    LoungeJob_Code: 'QWERTY',
    LoungeJob_Error_InvalidLoungeJobCode: 'QWERTY',
    LoungeJob_Error_InvalidToken: 'QWERTY',
    LoungeJob_Error_InvalidUserClaims: 'QWERTY',
    LoungeJob_Error_Job_Not_Found: 'QWERTY',
    LoungeJob_Error_LoungeJobExpired: 'QWERTY',
    LoungeJob_Error_LoungeJobNotYetAvailable: 'QWERTY',
    LoungeJob_Error_NoJobFound: 'QWERTY',
    MessageSent: 'QWERTY',
    MessageSentMessage: 'QWERTY',
    MoreInfo: 'QWERTY',
    NoAdvisorFound: 'QWERTY',
    OnlineBookingConfirmation: 'QWERTY',
    PackageSelectViewModel_Selection: 'QWERTY',
    PassengerVehicle: 'QWERTY',
    ReCaptchaInvalid: 'QWERTY',
    Registration: 'QWERTY',
    Repair: 'QWERTY',
    RepairList: 'QWERTY',
    Repairs: 'QWERTY',
    requestedupsell: 'QWERTY',
    RequestSent: 'QWERTY',
    SelectStateOfRegistration: 'QWERTY',
    SelectVehicleType: 'QWERTY',
    Sent: 'QWERTY',
    SubHeader_BookingConfirmation: 'QWERTY',
    SubHeader_BookingDetails: 'QWERTY',
    SubHeader_BookingDetails_Summary: 'QWERTY',
    SubHeader_DateSelect_PickADate: 'QWERTY',
    SubHeader_GarageDetection_TokenInvalid: 'QWERTY',
    SubHeader_Summary_AdditionalPackages: 'QWERTY',
    SubHeader_Summary_BookingSummary: 'QWERTY',
    SubHeader_ThanksForBooking: 'QWERTY',
    Success: 'QWERTY',
    TermsAndConditions: 'QWERTY',
    TermsAndConditionsDesc: 'QWERTY',
    Today: 'QWERTY',
    Total: 'QWERTY',
   
    must: 'QWERTY',
    ValidatorUserDate: 'QWERTY',
    VehicleValidationMessage: 'QWERTY',
    ViewTermsAndConditions: 'QWERTY',
    Welcome_Message: 'QWERTY',
    WelcomeOnlineBooking_Tag: 'QWERTY',
    You: 'QWERTY',
    YourAddress: 'QWERTY',
    YourAdvisor: 'QWERTY',
    YourBookingReference: 'QWERTY',
    YourDetails: 'QWERTY',
    YourRef: 'QWERTY',
    YourVehicle: 'QWERTY'
}
}
export {data}